#!/bin/bash
#double paran is the most recommended method

var1=$(( $1+$2))
var2=5
echo the value of var1*var2 is $(( $var1*$var2)) or it can also be expressed as $((var1*var2))
#increment var2
var2=$((var2+5))
echo $var2
#another method for incrementing
(( var2=var2+10 ))
echo $var2
